---
title: "Why Simulate? General Principles"
subtitle: "Role of Simulations. Principles, Design, and Anatomy"
author: Vladislav Morozov  
format:
  revealjs:
    include-in-header: 
      text: |
        <meta name="description" content=" (lecture notes slides)."/> 
    width: 1150
    slide-number: true
    sc-sb-title: true
    incremental: true   
    logo: ../../themes/favicon.ico
    footer: "Why Simulate and General Principles"
    footer-logo-link: "https://vladislav-morozov.github.io/simulations-course/"
    theme: ../../themes/slides_theme.scss
    toc: TRUE
    toc-depth: 2
    toc-title: Contents
    transition: convex
    transition-speed: fast
slide-level: 4
title-slide-attributes:
    data-background-color: "#3c165cff"
    data-footer: " "
filters:
  - reveal-header 
embed-resources: true
include-in-header: ../../themes/mathjax.html 
highlight-style: tango
open-graph:
    description: " (lecture note slides)" 
---






## Introduction {background="#00100F"}
 
  

### Lecture Info {background="#43464B"}

#### Learning Outcomes

This lecture is

<br>

By the end, you should be able to

- Describe

#### References

 

## Role of Monte Carlo Simulations {background="#00100F"}

### The Method Evaluation Problem {background="#43464B"}

#### What's The Point of Statistics?

In one sentence: 

<div class = rounded-box>


Developing new methods that allow user to learn parameters of interest from data

</div>

. . .

Parameters of interest:

- Depend on context
- Specified by the consumer of the method
- Goal of statistics: say if it can be learned and how

#### What Methods Do Consumers Want? 
 
<div class = rounded-box>

Consumers of statistical methods want to use methods that they know "<span class="highlight">work well</span>"

</div>

Natural: 

- A better tool gives better results
- Easier to defend choosing to use it

. . . 

<br>

<div class = left-color>

But what's "<span class="highlight">well</span>"?
</div>

#### What's "<span class="highlight">Well</span>"?

Modern understanding:


<div class = left-color>

A method works "<span class="highlight">well</span>" if some metric of interest "<span class="highlight">tends</span>" to "<span class="highlight">look good</span>" under a reasonably broad variety of data generating processes


</div>
 

- Metrics: bias, prediction risk, confidence interval coverage
- "<span class="highlight">Tends</span>": allow for some possibility of bad performance, but with low probability
- DGPs:  we don't love parametric assumptions

### Theoretical and Empirical Evaluation {background="#43464B"}

#### Evaluation Methods


<br>

Three main methods, in decreasing strength:

1. Finite sample theoretical guarantees
2. (Good) Monte Carlo simulations
3. Empirical validation

#### Theoretical Bounds


<div class = left-color>

Nonparametric finite sample bounds — best possible results

</div>
 
Usually possible for specific scenarios (bounded variables, bounded dimensions). Examples: 

- Bounds on lasso parrameter error [@Wainwright2019HighDimensionalStatisticsNonAsymptotic]
- The fundamental theorem of PAC learning + finite VC dimension results for certain classifier classses [@Shalev-Shwartz2014UnderstandingMachineLearning]
  

. . .
  
<div class = left-color>

In many problems <span class="highlight">impossible</span> to obtain useful guarantees

</div>

#### Place of Simulations

#### Empirical 


### Simulations {background="#43464B"}

#### Evaluation





#### Motivating Tool




can also prove that something doesn't work
#### Other Usage


#### "Monte Carlo" vs. Other Simulations

kinda the same

#### Limitations of Simulations

What


not everything can be simulated (images, text)

Or some models may also be intractable to train more than a few times


## Principles of Good Simulations {background="#00100F"}
 
#### The Three Key Characteristics

#### Reproducibility


## Anatomy of a Simulation {background="#00100F"}
 
#### The Four Steps



## Recap and Conclusions {background="#00100F"}
 
#### Recap


#### Next Questions


#### References {.allowframebreaks visibility="uncounted"}

::: {#refs}
:::
